//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pizzeria
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pizze
    {
        public int ID { get; set; }
        public string Nazwa { get; set; }
        public decimal Cena { get; set; }
        public int Skladnik1id { get; set; }
        public Nullable<int> Skladnik2id { get; set; }
        public Nullable<int> Skladnik3id { get; set; }
        public Nullable<int> Skladnik4id { get; set; }
    }
}
